# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09f82e44c062a0a5f4d2ce0ce3deb8c0cdb40708a640fa633435ccb3158a806f61779838336898448110f3ec2a89d8610e3e449ac49f3075cf5988a5a13038f3

test:
  secret_key_base: c5cc8462db530e386623d0b1cf651827594d773645c10f4e39a7f50ab88f5b1a97842234be66f2184595835def187e15b5d788d568f9114158d308b00009caf6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
